// HSN/SAC Code Finder
const hsnDatabase = [
  { code: '0100', description: 'Live cattle', gst: '5%' },
  { code: '0201', description: 'Meat of cattle - Fresh or chilled', gst: '5%' },
  { code: '0207', description: 'Meat of poultry - Fresh or chilled', gst: '5%' },
  { code: '0208', description: 'Other meat and edible meat offal', gst: '5%' },
  { code: '0301', description: 'Fish - Live', gst: '5%' },
  { code: '0302', description: 'Fish - Frozen', gst: '5%' },
  { code: '0304', description: 'Fish fillets and other fish meat', gst: '5%' },
  { code: '0305', description: 'Fish - Dried, salted or pickled', gst: '5%' },
  { code: '0306', description: 'Crustaceans', gst: '5%' },
  { code: '0307', description: 'Molluscs', gst: '5%' },
  { code: '0401', description: 'Milk and cream', gst: '5%' },
  { code: '0402', description: 'Milk and cream - Concentrated or sweetened', gst: '5%' },
  { code: '0403', description: 'Buttermilk, curdled milk', gst: '5%' },
  { code: '0404', description: 'Whey', gst: '5%' },
  { code: '0405', description: 'Butter and other fats derived from milk', gst: '5%' },
  { code: '0406', description: 'Cheese and curd', gst: '5%' },
  { code: '0407', description: 'Birds eggs - In shell, fresh', gst: '5%' },
  { code: '0408', description: 'Birds eggs - Not in shell', gst: '5%' },
  { code: '0409', description: 'Natural honey', gst: '5%' },
  { code: '0501', description: 'Human hair - Unworked', gst: '5%' },
  { code: '0502', description: 'Pigs, hogs, boar hair and other animal hair', gst: '5%' },
  { code: '0504', description: 'Guts, bladders and stomachs', gst: '5%' },
  { code: '0505', description: 'Skins and other animal products', gst: '5%' },
  { code: '0506', description: 'Bones and horn cores', gst: '5%' },
  { code: '0507', description: 'Ivory, tortoise shell, coral', gst: '5%' },
  { code: '0601', description: 'Bulbs, corms, tubers - Live', gst: '5%' },
  { code: '0602', description: 'Plants - Live', gst: '5%' },
  { code: '0701', description: 'Potatoes - Fresh or chilled', gst: '5%' },
  { code: '0702', description: 'Tomatoes - Fresh or chilled', gst: '5%' },
  { code: '0703', description: 'Onions, garlic - Fresh or chilled', gst: '5%' },
  { code: '0704', description: 'Cabbages and similar vegetables', gst: '5%' },
  { code: '0705', description: 'Lettuce and endive', gst: '5%' },
  { code: '0706', description: 'Carrots and similar vegetables', gst: '5%' },
  { code: '0707', description: 'Cucumbers and gherkins', gst: '5%' },
  { code: '0708', description: 'Legumes - Shelled or unshelled', gst: '5%' },
  { code: '0709', description: 'Other vegetables', gst: '5%' },
  { code: '0801', description: 'Coconuts, brazil nuts, cashew nuts', gst: '5%' },
  { code: '0802', description: 'Other nuts', gst: '5%' },
  { code: '0803', description: 'Bananas - Fresh or dried', gst: '5%' },
  { code: '0804', description: 'Dates, figs, pineapples - Fresh or dried', gst: '5%' },
  { code: '0805', description: 'Citrus fruit - Fresh or dried', gst: '5%' },
  { code: '0806', description: 'Grapes - Fresh or dried', gst: '5%' },
  { code: '0807', description: 'Melons and papayas', gst: '5%' },
  { code: '0808', description: 'Apples, pears and quinces - Fresh', gst: '5%' },
  { code: '0809', description: 'Apricots, cherries, peaches - Fresh', gst: '5%' },
  { code: '1001', description: 'Cereals - Wheat', gst: '5%' },
  { code: '1002', description: 'Cereals - Rye', gst: '5%' },
  { code: '1003', description: 'Cereals - Barley', gst: '5%' },
  { code: '1004', description: 'Cereals - Oats', gst: '5%' },
  { code: '1005', description: 'Cereals - Maize/Corn', gst: '5%' },
  { code: '1006', description: 'Cereals - Rice', gst: '5%' },
  { code: '1007', description: 'Cereals - Sorghum', gst: '5%' },
  { code: '1101', description: 'Wheat or meslin flour', gst: '5%' },
  { code: '1102', description: 'Cereal flour (other than wheat)', gst: '5%' },
  { code: '1103', description: 'Cereal groats, meal and pellets', gst: '5%' },
  { code: '1104', description: 'Cereal grains - Worked, hulled, pearl', gst: '5%' },
  { code: '1106', description: 'Flour and meal from oil seeds', gst: '5%' },
  { code: '1201', description: 'Oil seeds - Soybeans', gst: '5%' },
  { code: '1202', description: 'Oil seeds - Groundnuts', gst: '5%' },
  { code: '1203', description: 'Oil seeds - Copra', gst: '5%' },
  { code: '1204', description: 'Oil seeds - Sesame seeds', gst: '5%' },
  { code: '1205', description: 'Oil seeds - Rapeseeds', gst: '5%' },
  { code: '1207', description: 'Oil seeds - Sunflower seeds', gst: '5%' },
  { code: '1208', description: 'Oil seeds - Mustard seeds', gst: '5%' },
  { code: '1301', description: 'Lac; natural gums, resins', gst: '5%' },
  { code: '1302', description: 'Vegetable saps and extracts', gst: '5%' },
  { code: '1401', description: 'Vegetable plaiting materials', gst: '5%' },
  { code: '1501', description: 'Animal or vegetable fats and oils', gst: '5%' },
  { code: '1502', description: 'Animal or vegetable fats and oils', gst: '5%' },
  { code: '1503', description: 'Lard and other animal fats', gst: '5%' },
  { code: '1504', description: 'Fish oil and marine animal oils', gst: '5%' },
  { code: '1505', description: 'Wool grease and fatty substances', gst: '5%' },
  { code: '1506', description: 'Other animal fats and oils', gst: '5%' },
  { code: '1507', description: 'Soybean oil', gst: '5%' },
  { code: '1508', description: 'Groundnut oil', gst: '5%' },
  { code: '1509', description: 'Olive oil', gst: '5%' },
  { code: '1510', description: 'Other oils - Fixed vegetable oils', gst: '5%' },
  { code: '1511', description: 'Coconut, palm kernel, babassu oils', gst: '5%' },
  { code: '1512', description: 'Sunflower seed, safflower oil', gst: '5%' },
  { code: '1513', description: 'Coconut oil', gst: '5%' },
  { code: '1514', description: 'Rapeseed and mustard oils', gst: '5%' },
  { code: '1515', description: 'Other fixed vegetable oils', gst: '5%' },
  { code: '1516', description: 'Animal or vegetable fats and oils - Hydrogenated', gst: '5%' },
  { code: '1517', description: 'Margarine and similar preparations', gst: '5%' },
  { code: '1518', description: 'Animal or vegetable fats - Other', gst: '5%' },
  { code: '1520', description: 'Glycerol', gst: '5%' },
  { code: '1521', description: 'Vegetable waxes and other plant waxes', gst: '5%' },
  { code: '1522', description: 'Degras; residues from fats', gst: '5%' },
  { code: '1601', description: 'Sausages and similar products - Meat, offal', gst: '5%' },
  { code: '1602', description: 'Prepared or preserved meat, offal', gst: '5%' },
  { code: '1603', description: 'Meat or offal extracts and juices', gst: '5%' },
  { code: '1604', description: 'Prepared or preserved fish', gst: '5%' },
  { code: '1605', description: 'Crustaceans, molluscs - Prepared, preserved', gst: '5%' },
  { code: '1701', description: 'Sugars and sugar syrups - Cane sugar', gst: '5%' },
  { code: '1702', description: 'Sugars and sugar syrups - Other', gst: '5%' },
  { code: '1703', description: 'Molasses', gst: '5%' },
  { code: '1704', description: 'Sugar confectionery', gst: '5%' },
  { code: '1801', description: 'Cocoa beans', gst: '5%' },
  { code: '1802', description: 'Cocoa shells, husks, skins', gst: '5%' },
  { code: '1803', description: 'Cocoa paste and cocoa butter', gst: '5%' },
  { code: '1804', description: 'Cocoa powder', gst: '5%' },
  { code: '1805', description: 'Cocoa butter, fat and oil', gst: '5%' },
  { code: '1901', description: 'Malt extract', gst: '5%' },
  { code: '1902', description: 'Pasta products', gst: '5%' },
  { code: '1903', description: 'Tapioca and substitutes - Starch products', gst: '5%' },
  { code: '1904', description: 'Prepared cereal foods', gst: '5%' },
  { code: '1905', description: 'Bread, pastry, biscuits', gst: '5%' },
  { code: '2001', description: 'Vegetables - Preserved by salt', gst: '5%' },
  { code: '2002', description: 'Tomatoes - Prepared or preserved', gst: '5%' },
  { code: '2003', description: 'Mushrooms - Prepared or preserved', gst: '5%' },
  { code: '2004', description: 'Vegetables - Prepared or preserved - Other', gst: '5%' },
  { code: '2005', description: 'Other vegetables - Prepared or preserved', gst: '5%' },
  { code: '2008', description: 'Fruit, nuts - Prepared or preserved', gst: '5%' },
  { code: '2009', description: 'Fruit juices and vegetable juices', gst: '5%' },
  { code: '2101', description: 'Extracts, essences and concentrates of coffee', gst: '5%' },
  { code: '2102', description: 'Yeasts; other microorganisms', gst: '5%' },
  { code: '2103', description: 'Salt and salt mixtures and sea water', gst: '5%' },
  { code: '2104', description: 'Soups and broths', gst: '5%' },
  { code: '2105', description: 'Ice cream and similar products', gst: '5%' },
  { code: '2106', description: 'Food preparations (not elsewhere specified)', gst: '5%' },
  { code: '2201', description: 'Waters - Mineral, aerated', gst: '5%' },
  { code: '2202', description: 'Beverages - Non-alcoholic (except water and juice)', gst: '5%' },
  { code: '2203', description: 'Beer', gst: '0%' },
  { code: '2204', description: 'Wine of fresh grapes', gst: '0%' },
  { code: '2205', description: 'Vermouth and similar wine', gst: '0%' },
  { code: '2206', description: 'Other fermented beverages', gst: '0%' },
  { code: '2207', description: 'Ethyl alcohol and aqua vitae', gst: '0%' },
  { code: '2208', description: 'Spirits, liqueurs', gst: '0%' },
  { code: '2209', description: 'Vinegar', gst: '5%' },
  { code: '2401', description: 'Tobacco leaves', gst: '5%' },
  { code: '2402', description: 'Cigars, cigarettes', gst: '28%' },
  { code: '2403', description: 'Smoking tobacco', gst: '28%' },
  { code: '2501', description: 'Salt', gst: '5%' },
  { code: '2502', description: 'Mineral salts and products', gst: '5%' },
  { code: '2503', description: 'Sulfur', gst: '5%' },
  { code: '2504', description: 'Natural phosphates', gst: '5%' },
  { code: '2505', description: 'Natural sands', gst: '5%' },
  { code: '2506', description: 'Quartz; quartzite', gst: '5%' },
  { code: '2507', description: 'Kaolin (China clay)', gst: '5%' },
  { code: '2508', description: 'Feldpar; leucite; nepheline', gst: '5%' },
  { code: '2509', description: 'Chalk', gst: '5%' },
  { code: '2510', description: 'Natural calcium phosphates', gst: '5%' },
  { code: '2511', description: 'Natural barium sulfate (barytes)', gst: '5%' },
  { code: '2512', description: 'Siliceous fossil meals', gst: '5%' },
  { code: '2513', description: 'Pumice, emery, corundum', gst: '5%' },
  { code: '2514', description: 'Slate', gst: '5%' },
  { code: '2515', description: 'Marble and travertine', gst: '5%' },
  { code: '2516', description: 'Granite and other monumental stone', gst: '5%' },
  { code: '2517', description: 'Pebbles, gravel, broken rock', gst: '5%' },
  { code: '2518', description: 'Dolomite; dolomitic limestone', gst: '5%' },
  { code: '2519', description: 'Natural magnesium carbonate (magnesite)', gst: '5%' },
  { code: '2520', description: 'Gypsum, anhydrite', gst: '5%' },
  { code: '2521', description: 'Limestone flux; limestone and other calcium carbonate', gst: '5%' },
  { code: '2522', description: 'Quicklime, slaked lime', gst: '5%' },
  { code: '2523', description: 'Portland cement; cement clinkers', gst: '5%' },
  { code: '2524', description: 'Asbestos', gst: '5%' },
  { code: '2525', description: 'Mica', gst: '5%' },
  { code: '2526', description: 'Natural steatite', gst: '5%' },
  { code: '2528', description: 'Borates and natural boracites', gst: '5%' },
  { code: '2530', description: 'Mineral substances (not elsewhere specified)', gst: '5%' },
  { code: '2607', description: 'Lead ores and concentrates', gst: '2.5%' },
  { code: '2608', description: 'Zinc ores and concentrates', gst: '2.5%' },
  { code: '2609', description: 'Tin ores and concentrates', gst: '2.5%' },
  { code: '2610', description: 'Copper ores and concentrates', gst: '2.5%' },
  { code: '2701', description: 'Coal; briquettes', gst: '5%' },
  { code: '2702', description: 'Lignite; agglomerated lignite', gst: '5%' },
  { code: '2703', description: 'Peat', gst: '5%' },
  { code: '2704', description: 'Coke and semi-coke', gst: '5%' },
  { code: '2705', description: 'Coal gas, water gas, producer gas', gst: '5%' },
  { code: '2706', description: 'Tar from coal, shale oil', gst: '5%' },
  { code: '2707', description: 'Oils and other products of coal distillation', gst: '5%' },
  { code: '2708', description: 'Pitch and pitch coke', gst: '5%' },
  { code: '2709', description: 'Petroleum crude oil', gst: '0%' },
  { code: '2710', description: 'Petroleum oils and oils from bituminous minerals', gst: '5%' },
  { code: '2711', description: 'Petroleum gases and other gaseous hydrocarbons', gst: '5%' },
  { code: '2712', description: 'Petroleum jelly; paraffin wax', gst: '5%' },
  { code: '2713', description: 'Petroleum coke', gst: '5%' },
  { code: '2714', description: 'Bitumen and asphalt; bituminous mixtures', gst: '5%' },
  { code: '2715', description: 'Bituminous mixtures based on asphalt or mineral materials', gst: '5%' },
  { code: '2801', description: 'Fluorine; chlorine; bromine; iodine', gst: '5%' },
  { code: '2802', description: 'Sulfur, sublimed or precipitated', gst: '5%' },
  { code: '2803', description: 'Carbon (carbon blacks and other forms)', gst: '5%' },
  { code: '2804', description: 'Hydrogen; rare gases; other non-metals', gst: '5%' },
  { code: '2805', description: 'Alkali or alkaline earth metals', gst: '5%' },
  { code: '2806', description: 'Hydrochloric acid; other non-metallic acids', gst: '5%' },
  { code: '2807', description: 'Sulfuric acid; other inorganic acids', gst: '5%' },
  { code: '2808', description: 'Nitric acid', gst: '5%' },
  { code: '2809', description: 'Diphosphorus pentoxide; phosphoric acid', gst: '5%' },
  { code: '2810', description: 'Phosphides; other inorganic compounds', gst: '5%' },
  { code: '3101', description: 'Animal or vegetable fertilizers', gst: '5%' },
  { code: '3102', description: 'Mineral or chemical fertilizers, nitrogenous', gst: '5%' },
  { code: '3103', description: 'Mineral or chemical fertilizers, phosphatic', gst: '5%' },
  { code: '3104', description: 'Mineral or chemical fertilizers, potassic', gst: '5%' },
  { code: '3105', description: 'Fertilizers (other, multiple nutrients)', gst: '5%' },
  { code: '3201', description: 'Tanning extracts; tannic acids', gst: '5%' },
  { code: '3202', description: 'Dyeing and tanning preparations; vegetable materials', gst: '5%' },
  { code: '3203', description: 'Coloring matter of vegetable origin', gst: '5%' },
  { code: '3204', description: 'Organic synthetic coloring matter', gst: '5%' },
  { code: '3205', description: 'Coloring matter and preparations (other)', gst: '5%' },
  { code: '3206', description: 'Other coloring matter; inorganic pigments', gst: '5%' },
  { code: '3207', description: 'Paints and varnishes', gst: '18%' },
  { code: '3208', description: 'Paints and varnishes based on synthetic polymers', gst: '18%' },
  { code: '3209', description: 'Paints, varnishes (other), including enamels', gst: '18%' },
  { code: '3210', description: 'Other paintings, including lacquers, distempers', gst: '18%' },
  { code: '3211', description: 'Dried colors; color preparations and colorants', gst: '5%' },
  { code: '3212', description: 'Pigments and preparations dispersed in non-aqueous media', gst: '5%' },
  { code: '3213', description: 'Artists colors; preparations; paints for use by artists', gst: '12%' },
  { code: '3214', description: 'Putty; caulking putties', gst: '18%' },
  { code: '3215', description: 'Inks', gst: '18%' },
  { code: '3301', description: 'Essential oils; oleoresins; concentrates', gst: '12%' },
  { code: '3302', description: 'Mixtures of odiferous substances; preparations', gst: '12%' },
  { code: '3303', description: 'Perfumes and toilet waters', gst: '28%' },
  { code: '3304', description: 'Beauty, make-up, skin-care preparations', gst: '28%' },
  { code: '3305', description: 'Hair-care preparations', gst: '28%' },
  { code: '3306', description: 'Oral or dental hygiene preparations', gst: '18%' },
  { code: '3307', description: 'Pre-shave, shaving, after-shave preparations', gst: '28%' },
  { code: '3401', description: 'Soap; organic surface-active agents', gst: '18%' },
  { code: '3402', description: 'Organic surface-active agents; detergents', gst: '18%' },
  { code: '3403', description: 'Lubricating preparations', gst: '18%' },
  { code: '3404', description: 'Artificial waxes; prepared waxes', gst: '18%' },
  { code: '3405', description: 'Polishes and creams for footwear, furniture', gst: '18%' },
  { code: '3406', description: 'Candles, tapers, wicks', gst: '18%' },
  { code: '3407', description: 'Modeling pastes; other preparations', gst: '18%' },
  { code: '3501', description: 'Casein', gst: '5%' },
  { code: '3502', description: 'Albumins, albuminates; gelatin; proteinaceous substances', gst: '5%' },
  { code: '3503', description: 'Gelatin (excluding bone glue) and glues derived from it', gst: '5%' },
  { code: '3504', description: 'Peptones and their derivatives; other proteinaceous substances', gst: '5%' },
  { code: '3505', description: 'Dextrins; inulin; other modified starches', gst: '5%' },
  { code: '3506', description: 'Glues and adhesives', gst: '18%' },
  { code: '3507', description: 'Enzymes', gst: '5%' },
  { code: '3601', description: 'Explosives; pyrotechnic products', gst: '28%' },
  { code: '3602', description: 'Matches', gst: '12%' },
  { code: '3603', description: 'Fuses; percussion caps; detonators', gst: '28%' },
  { code: '3604', description: 'Fireworks, signaling flares', gst: '28%' },
  { code: '3605', description: 'Matches of types other than safety matches', gst: '12%' },
  { code: '3606', description: 'Ferro-cerium and other pyrophoric alloys', gst: '12%' },
  { code: '3701', description: 'Photographic plates and film (sensitized)', gst: '5%' },
  { code: '3702', description: 'Photographic film and photographic plates', gst: '5%' },
  { code: '3703', description: 'Photographic paper, paperboard, textiles (light-sensitive)', gst: '5%' },
  { code: '3704', description: 'Photographic plates, film (exposed and developed)', gst: '5%' },
  { code: '3705', description: 'Photographic plates; film; paper; paperboard (other)', gst: '5%' },
  { code: '3706', description: 'Cinematographic film (exposed and developed)', gst: '5%' },
  { code: '3707', description: 'Chemical preparations for photographic uses', gst: '12%' },
  { code: '3801', description: 'Activated carbon; other activated products', gst: '5%' },
  { code: '3802', description: 'Animal charcoal', gst: '5%' },
  { code: '3803', description: 'Tall oil', gst: '5%' },
  { code: '3804', description: 'Residual lyes', gst: '5%' },
  { code: '3805', description: 'Sulphite cellulose waste liquor', gst: '5%' },
  { code: '3806', description: 'Rosin and rosin oils', gst: '5%' },
  { code: '3807', description: 'Wood tar; wood creosote; wood pitch; turpentine', gst: '5%' },
  { code: '3808', description: 'Insecticides, rodenticides, fungicides', gst: '12%' },
  { code: '3809', description: 'Finishing agents, dye carriers', gst: '12%' },
  { code: '3810', description: 'Pickling preparations for metals; fluxes', gst: '12%' },
  { code: '3811', description: 'Anti-knock preparations and other preparations', gst: '12%' },
  { code: '3812', description: 'Prepared rubber accelerators', gst: '12%' },
  { code: '3813', description: 'Preparations and charges for fire extinguishers', gst: '12%' },
  { code: '3814', description: 'Organic composite solvents and thinners', gst: '12%' },
  { code: '3815', description: 'Reaction initiators, reaction accelerators', gst: '12%' },
  { code: '3816', description: 'Refractory cements, mortars, concrete', gst: '12%' },
  { code: '3817', description: 'Mixed alkylbenzenes; mixed alkylnaphthales', gst: '12%' },
  { code: '3818', description: 'Distilled water; conductivity water', gst: '12%' },
  { code: '3819', description: 'Hydraulic fluids based on mineral oils', gst: '12%' },
  { code: '3820', description: 'Anti-freezing preparations; de-icing preparations', gst: '12%' },
  { code: '3821', description: 'Diagnostic or laboratory reagents', gst: '12%' },
  { code: '3822', description: 'Diagnostic reagents for determination of blood groups', gst: '5%' },
  { code: '3823', description: 'Industrial monocarboxylic fatty acids', gst: '5%' },
  { code: '3824', description: 'Preparations specified in Note 3 to this chapter', gst: '12%' },
  { code: '3825', description: 'Residual products of chemical or allied industries', gst: '12%' },
  { code: '3826', description: 'Biodiesel and mixtures thereof', gst: '5%' },
  { code: '3827', description: 'Dithionites; sulfoxylates', gst: '12%' },
  { code: '3828', description: 'Chlorides of isocyanuric acid (cyanuric chloride)', gst: '12%' },
  { code: '3829', description: 'Leather pretannages; other preparations', gst: '12%' },
  { code: '3901', description: 'Polymers of ethylene, in primary forms', gst: '18%' },
  { code: '3902', description: 'Polymers of propylene or of other olefins', gst: '18%' },
  { code: '3903', description: 'Polymers of styrene, in primary forms', gst: '18%' },
  { code: '3904', description: 'Polymers of vinyl chloride or of other halogenated olefins', gst: '18%' },
  { code: '3905', description: 'Polymers of vinyl acetate or of other vinyl esters', gst: '18%' },
  { code: '3906', description: 'Acrylic polymers, in primary forms', gst: '18%' },
  { code: '3907', description: 'Polyacetals; other polyethers', gst: '18%' },
  { code: '3908', description: 'Polyamides, in primary forms', gst: '18%' },
  { code: '3909', description: 'Amino-resins; phenolic resins; polyurethanes', gst: '18%' },
  { code: '3910', description: 'Silicones, in primary forms', gst: '18%' },
  { code: '3911', description: 'Petroleum resins, coumarone indene resins', gst: '18%' },
  { code: '3912', description: 'Cellulose and its chemical derivatives', gst: '18%' },
  { code: '3913', description: 'Natural polymers (alginates; pectinates)', gst: '18%' },
  { code: '3914', description: 'Ion-exchangers based on polymers', gst: '18%' },
  { code: '3915', description: 'Waste, parings, scrap of plastics', gst: '5%' },
  { code: '3916', description: 'Monofilament of plastics; cross-linked elastomeric yarn', gst: '18%' },
  { code: '3917', description: 'Tubes, pipes and hoses, plastics', gst: '18%' },
  { code: '3918', description: 'Flooring of plastics', gst: '18%' },
  { code: '3919', description: 'Self-adhesive plates, sheets, film, foil, tape, strip', gst: '18%' },
  { code: '3920', description: 'Other plates, sheets, film, foil, tape, strip, plastics', gst: '18%' },
  { code: '3921', description: 'Other plates, sheets, film, foil and strip, of plastics', gst: '18%' },
  { code: '3922', description: 'Lavatory seats and covers, plastics', gst: '18%' },
  { code: '3923', description: 'Articles for conveyance of goods, plastics', gst: '18%' },
  { code: '3924', description: 'Tableware, kitchenware, household articles, plastics', gst: '18%' },
  { code: '3925', description: 'Builders ware, plastics', gst: '18%' },
  { code: '3926', description: 'Other articles, plastics', gst: '18%' },
  { code: '4001', description: 'Natural rubber in primary forms', gst: '5%' },
  { code: '4002', description: 'Synthetic rubber, in primary forms', gst: '5%' },
  { code: '4003', description: 'Reclaimed rubber; waste, parings, scrap of rubber', gst: '5%' },
  { code: '4004', description: 'Waste, parings and scrap of rubber', gst: '5%' },
  { code: '4005', description: 'Compounded rubber, unvulcanized', gst: '5%' },
  { code: '4006', description: 'Other forms of compounded rubber', gst: '5%' },
  { code: '4007', description: 'Vulcanized rubber thread and cord', gst: '5%' },
  { code: '4008', description: 'Plates, sheets, strip, rods and profile shapes, rubber', gst: '5%' },
  { code: '4009', description: 'Tubes, pipes and hoses, rubber', gst: '5%' },
  { code: '4010', description: 'Conveyer belts and belting, rubber', gst: '5%' },
  { code: '4011', description: 'Pneumatic tyres, new of rubber', gst: '12%' },
  { code: '4012', description: 'Pneumatic tyres, used; tyres, solid or cushioned', gst: '12%' },
  { code: '4013', description: 'Inner tubes and flaps, rubber', gst: '5%' },
  { code: '4014', description: 'Hygienic or pharmaceutical articles, rubber', gst: '5%' },
  { code: '4015', description: 'Articles of apparel and clothing accessories, rubber', gst: '5%' },
  { code: '4016', description: 'Other articles of rubber', gst: '18%' },
  { code: '5001', description: 'Silk-worm cocoons suitable for reeling', gst: '5%' },
  { code: '5002', description: 'Raw silk (not thrown)', gst: '5%' },
  { code: '5003', description: 'Silk waste (including cocoons unsuitable for reeling)', gst: '5%' },
  { code: '5004', description: 'Silk yarn (other than spun silk yarn), not put up', gst: '5%' },
  { code: '5005', description: 'Yarn spun from silk waste, not put up', gst: '5%' },
  { code: '5006', description: 'Silk yarn and yarn spun from silk waste, put up', gst: '5%' },
  { code: '5007', description: 'Fabrics of silk or silk waste', gst: '5%' },
  { code: '5101', description: 'Wool, greasy, including fleece-washed wool', gst: '5%' },
  { code: '5102', description: 'Fine or coarse animal hair; horsehair yarn', gst: '5%' },
  { code: '5103', description: 'Waste of wool or of fine or coarse animal hair', gst: '5%' },
  { code: '5104', description: 'Noils of wool or of fine animal hair', gst: '5%' },
  { code: '5105', description: 'Wool and fine animal hair, carded or combed', gst: '5%' },
  { code: '5106', description: 'Wool yarn, not put up for retail sale', gst: '5%' },
  { code: '5107', description: 'Yarn of fine animal hair, not put up for retail sale', gst: '5%' },
  { code: '5108', description: 'Yarn of coarse animal hair or of horsehair', gst: '5%' },
  { code: '5109', description: 'Yarn of wool or of fine or coarse animal hair, put up', gst: '5%' },
  { code: '5110', description: 'Yarn of wool, fine or coarse animal hair or horsehair', gst: '5%' },
  { code: '5111', description: 'Fabrics of carded wool', gst: '5%' },
  { code: '5112', description: 'Other fabrics of wool or of fine animal hair', gst: '5%' },
  { code: '5113', description: 'Fabrics of coarse animal hair or horsehair', gst: '5%' },
  { code: '5201', description: 'Cotton yarn, not put up for retail sale', gst: '5%' },
  { code: '5202', description: 'Cotton yarn, put up for retail sale', gst: '5%' },
  { code: '5203', description: 'Cotton fabric', gst: '5%' },
  { code: '5204', description: 'Cotton fabric (other), unbleached', gst: '5%' },
  { code: '5205', description: 'Cotton yarn (other)', gst: '5%' },
  { code: '5206', description: 'Bleached yarn, cotton', gst: '5%' },
  { code: '5207', description: 'Dyed cotton yarn', gst: '5%' },
  { code: '5208', description: 'Cotton fabrics', gst: '5%' },
  { code: '5209', description: 'Cotton woven fabrics (other)', gst: '5%' },
  { code: '5210', description: 'Cotton woven fabrics', gst: '5%' },
  { code: '5211', description: 'Printed cotton woven fabrics', gst: '5%' },
  { code: '5212', description: 'Other cotton woven fabric', gst: '5%' },
  { code: '5301', description: 'Flax straw and broken', gst: '5%' },
  { code: '5302', description: 'Flax fibre', gst: '5%' },
  { code: '5303', description: 'Jute and other textile bast fibres', gst: '5%' },
  { code: '5304', description: 'Sisal and other agave fibres', gst: '5%' },
  { code: '5305', description: 'Coconut, abaca, ramie and other vegetable fibres', gst: '5%' },
  { code: '5306', description: 'Flax yarn', gst: '5%' },
  { code: '5307', description: 'Yarn of jute or of other textile bast fibres', gst: '5%' },
  { code: '5308', description: 'Yarn of other vegetable textile fibres', gst: '5%' },
  { code: '5309', description: 'Woven fabric of flax', gst: '5%' },
  { code: '5310', description: 'Woven fabric of jute or other textile bast fibres', gst: '5%' },
  { code: '5311', description: 'Woven fabric of other vegetable textile fibres', gst: '5%' },
  { code: '5312', description: 'Fabrics of vegetable textile fibres (other)', gst: '5%' },
  { code: '5401', description: 'Synthetic filament yarn', gst: '5%' },
  { code: '5402', description: 'Artificial filament yarn', gst: '5%' },
  { code: '5403', description: 'Artificial staple fibres', gst: '5%' },
  { code: '5404', description: 'Synthetic monofilament', gst: '5%' },
  { code: '5405', description: 'Yarn of synthetic filament or staple fibres', gst: '5%' },
  { code: '5406', description: 'Yarn of artificial filament or staple fibres', gst: '5%' },
  { code: '5407', description: 'Woven fabrics of synthetic filament yarn', gst: '5%' },
  { code: '5408', description: 'Woven fabrics of artificial filament yarn', gst: '5%' },
  { code: '5501', description: 'Synthetic staple fibres', gst: '5%' },
  { code: '5502', description: 'Artificial staple fibres', gst: '5%' },
  { code: '5503', description: 'Synthetic staple fibres, carded, combed', gst: '5%' },
  { code: '5504', description: 'Artificial staple fibres, carded, combed', gst: '5%' },
  { code: '5505', description: 'Waste of synthetic or artificial staple fibres', gst: '5%' },
  { code: '5506', description: 'Synthetic staple fibre yarn, not put up', gst: '5%' },
  { code: '5507', description: 'Artificial staple fibre yarn, not put up', gst: '5%' },
  { code: '5508', description: 'Synthetic staple fibre yarn, put up', gst: '5%' },
  { code: '5509', description: 'Artificial staple fibre yarn, put up', gst: '5%' },
  { code: '5510', description: 'Yarn of synthetic staple fibres', gst: '5%' },
  { code: '5511', description: 'Yarn of artificial staple fibres', gst: '5%' },
  { code: '5512', description: 'Woven fabrics of synthetic staple fibres', gst: '5%' },
  { code: '5513', description: 'Woven fabrics of synthetic staple fibres', gst: '5%' },
  { code: '5514', description: 'Woven fabrics of synthetic staple fibres (other)', gst: '5%' },
  { code: '5515', description: 'Other woven fabrics of synthetic staple fibres', gst: '5%' },
  { code: '5516', description: 'Woven fabrics of artificial staple fibres', gst: '5%' },
  { code: '5517', description: 'Other woven fabrics of artificial staple fibres', gst: '5%' },
  { code: '5518', description: 'Fabrics of synthetic or artificial staple fibres (other)', gst: '5%' },
  { code: '5519', description: 'Other fabrics of synthetic or artificial staple fibres', gst: '5%' },
  { code: '5601', description: 'Carpets and other textile floor coverings (other), knotted', gst: '12%' },
  { code: '5602', description: 'Other carpets and textile floor coverings', gst: '12%' },
  { code: '5603', description: 'Nonwovens', gst: '12%' },
  { code: '5604', description: 'Rubber thread and cord, textile covered', gst: '12%' },
  { code: '5605', description: 'Metallised yarn', gst: '12%' },
  { code: '5606', description: 'Gimped yarn and strip; braids and ornamental trimmings', gst: '12%' },
  { code: '5607', description: 'Twine, cordage, ropes and cables', gst: '12%' },
  { code: '5608', description: 'Knotted netting of twine, cordage, rope or cable', gst: '12%' },
  { code: '5609', description: 'Articles of yarn, twine, cordage, rope or cable', gst: '12%' },
  { code: '5701', description: 'Carpets and other textile floor coverings', gst: '12%' },
  { code: '5702', description: 'Carpets and other textile floor coverings (other)', gst: '12%' },
  { code: '5703', description: 'Carpets and other textile floor coverings (other)', gst: '12%' },
  { code: '5704', description: 'Carpets and other textile floor coverings (other)', gst: '12%' },
  { code: '5705', description: 'Other carpets and textile floor coverings (other)', gst: '12%' },
  { code: '5801', description: 'Velvets and plushes', gst: '5%' },
  { code: '5802', description: 'Terry fabrics and similar looped pile fabrics', gst: '5%' },
  { code: '5803', description: 'Gauze', gst: '5%' },
  { code: '5804', description: 'Tulles and other net fabrics', gst: '5%' },
  { code: '5805', description: 'Lace', gst: '5%' },
  { code: '5806', description: 'Narrow woven fabrics', gst: '5%' },
  { code: '5807', description: 'Labels, badges and similar articles', gst: '5%' },
  { code: '5808', description: 'Braids in the piece', gst: '5%' },
  { code: '5809', description: 'Woven fabrics of metal thread', gst: '12%' },
  { code: '5810', description: 'Embroidery in the piece, in strips or in motifs', gst: '5%' },
  { code: '5811', description: 'Quilted textile products', gst: '5%' },
  { code: '5901', description: 'Textile fabrics coated with gum or amylaceous substances', gst: '5%' },
  { code: '5902', description: 'Tyre cord fabric of high-tenacity yarn', gst: '5%' },
  { code: '5903', description: 'Textile fabrics impregnated with plastics', gst: '12%' },
  { code: '5904', description: 'Linoleum', gst: '12%' },
  { code: '5905', description: 'Textile fabrics, otherwise coated, covered or laminated', gst: '12%' },
  { code: '5906', description: 'Rubberised textile fabrics', gst: '12%' },
  { code: '5907', description: 'Textile fabrics otherwise impregnated, coated, covered', gst: '12%' },
  { code: '5908', description: 'Textile wicks; tubular knit fabric; other products', gst: '12%' },
  { code: '5909', description: 'Textile hose and similar tubular article', gst: '12%' },
  { code: '5910', description: 'Transmission or conveyor belts of textile', gst: '12%' },
  { code: '5911', description: 'Textile products and articles for technical use', gst: '12%' },
  { code: '6001', description: 'Pile fabrics and similar looped pile fabrics', gst: '5%' },
  { code: '6002', description: 'Knitted or crocheted fabrics of a width', gst: '5%' },
  { code: '6003', description: 'Knitted or crocheted fabrics of a width (other)', gst: '5%' },
  { code: '6004', description: 'Knitted or crocheted fabrics of a width (other)', gst: '5%' },
  { code: '6005', description: 'Warp knit fabrics', gst: '5%' },
  { code: '6006', description: 'Other knitted or crocheted fabrics', gst: '5%' },
  { code: '6101', description: 'Pullovers, cardigans, and similar articles', gst: '12%' },
  { code: '6102', description: 'Pullovers, cardigans, and similar articles (other)', gst: '12%' },
  { code: '6103', description: 'Mens/boys suits, ensembles, jackets and similar', gst: '12%' },
  { code: '6104', description: 'Womens/girls suits, ensembles, jackets and similar', gst: '12%' },
  { code: '6105', description: 'Mens/boys shirts', gst: '12%' },
  { code: '6106', description: 'Womens/girls blouses and shirts', gst: '12%' },
  { code: '6107', description: 'Mens/boys underwear', gst: '12%' },
  { code: '6108', description: 'Womens/girls underwear', gst: '12%' },
  { code: '6109', description: 'T-shirts and vests', gst: '12%' },
  { code: '6110', description: 'Pullovers (other), cardigans and similar', gst: '12%' },
  { code: '6111', description: 'Babies garments and clothing accessories', gst: '0%' },
  { code: '6112', description: 'Track suits, ski suits and similar', gst: '12%' },
  { code: '6113', description: 'Garments (other), knitted or crocheted', gst: '12%' },
  { code: '6114', description: 'Garments and clothing accessories (other)', gst: '12%' },
  { code: '6115', description: 'Hosiery', gst: '12%' },
  { code: '6116', description: 'Gloves, mitts and mittens', gst: '12%' },
  { code: '6117', description: 'Other made up clothing accessories', gst: '12%' },
  { code: '6201', description: 'Mens/boys overcoats, carcoats and similar', gst: '12%' },
  { code: '6202', description: 'Womens/girls overcoats, car coats and similar', gst: '12%' },
  { code: '6203', description: 'Mens/boys suits, ensembles, jackets, blazers', gst: '12%' },
  { code: '6204', description: 'Womens/girls suits, ensembles, jackets', gst: '12%' },
  { code: '6205', description: 'Mens/boys shirts', gst: '12%' },
  { code: '6206', description: 'Womens/girls blouses and shirts', gst: '12%' },
  { code: '6207', description: 'Mens/boys nightshirts, nightgowns and underwear', gst: '12%' },
  { code: '6208', description: 'Womens/girls nightgowns and underwear', gst: '12%' },
  { code: '6209', description: 'Babies garments and clothing accessories', gst: '0%' },
  { code: '6210', description: 'Garments made up from fabrics (other)', gst: '12%' },
  { code: '6211', description: 'Track suits, ski suits, swimming suits', gst: '12%' },
  { code: '6212', description: 'Brassieres, corsets and similar', gst: '12%' },
  { code: '6213', description: 'Handkerchiefs, shawls, scarves, mufflers', gst: '12%' },
  { code: '6214', description: 'Shawls, scarves, mufflers, veils and similar', gst: '12%' },
  { code: '6215', description: 'Ties, bow ties and cravats', gst: '12%' },
  { code: '6216', description: 'Gloves, mittens and mitts', gst: '12%' },
  { code: '6217', description: 'Other made up clothing accessories', gst: '12%' },
  { code: '6301', description: 'Blankets and travelling rugs', gst: '12%' },
  { code: '6302', description: 'Bedding and similar furnishing articles', gst: '12%' },
  { code: '6303', description: 'Curtains and interior blinds', gst: '12%' },
  { code: '6304', description: 'Other furnishing articles', gst: '12%' },
  { code: '6305', description: 'Sacks and bags for the conveyance of goods', gst: '12%' },
  { code: '6306', description: 'Tarpaulins, awnings, sunblinds; camping goods', gst: '12%' },
  { code: '6307', description: 'Other made up textile articles', gst: '12%' },
  { code: '6308', description: 'Sets of textile fabrics or made up articles', gst: '12%' },
  { code: '6309', description: 'Worn clothing and worn textile articles', gst: '5%' },
  { code: '6310', description: 'Used or new rags, scrap twine, rope, cables', gst: '5%' },
  { code: '6401', description: 'Footwear with leather upper', gst: '12%' },
  { code: '6402', description: 'Footwear with outer soles of rubber/plastics', gst: '12%' },
  { code: '6403', description: 'Footwear with outer soles of leather', gst: '12%' },
  { code: '6404', description: 'Footwear with textile upper', gst: '12%' },
  { code: '6405', description: 'Other footwear', gst: '12%' },
  { code: '6406', description: 'Parts of footwear; removable insoles', gst: '12%' },
  { code: '6501', description: 'Hats and other headgear, knitted or crocheted', gst: '12%' },
  { code: '6502', description: 'Hats and other headgear, not knitted', gst: '12%' },
  { code: '6503', description: 'Hats and other headgear of textile materials', gst: '12%' },
  { code: '6504', description: 'Hats and other headgear of leather', gst: '12%' },
  { code: '6505', description: 'Hats and other headgear made up from lace, felt', gst: '12%' },
  { code: '6506', description: 'Other hats and headgear', gst: '12%' },
  { code: '6507', description: 'Head-bands, linings, covers; hair-nets', gst: '12%' },
  { code: '7001', description: 'Cullet and other waste and scrap of glass', gst: '5%' },
  { code: '7002', description: 'Glass in the mass (not worked)', gst: '5%' },
  { code: '7003', description: 'Cast glass and rolled glass', gst: '5%' },
  { code: '7004', description: 'Wired glass', gst: '5%' },
  { code: '7005', description: 'Float glass and surface ground glass', gst: '5%' },
  { code: '7006', description: 'Glass of soda-lime silica type', gst: '5%' },
  { code: '7007', description: 'Toughened (tempered) safety glass', gst: '5%' },
  { code: '7008', description: 'Laminated safety glass', gst: '5%' },
  { code: '7009', description: 'Glass, multiple-walled insulating units', gst: '5%' },
  { code: '7010', description: 'Carboys, bottles, jars, and other glass containers', gst: '5%' },
  { code: '7011', description: 'Stoneware and earthenware articles', gst: '12%' },
  { code: '7013', description: 'Glassware for table or kitchen purposes', gst: '12%' },
  { code: '7014', description: 'Signalling glassware and optical elements', gst: '5%' },
  { code: '7015', description: 'Clock or watch glasses and similar watch glasses', gst: '12%' },
  { code: '7016', description: 'Paving blocks, bricks, tiles and other articles', gst: '12%' },
  { code: '7017', description: 'Laboratory, hygienic or pharmaceutical glassware', gst: '5%' },
  { code: '7018', description: 'Glass beads, pearls and similar small glass articles', gst: '12%' },
  { code: '7019', description: 'Glass fibres and articles thereof', gst: '12%' },
  { code: '7020', description: 'Other articles of glass', gst: '12%' },
  { code: '7101', description: 'Pearls, natural or cultured', gst: '0%' },
  { code: '7102', description: 'Diamonds, whether or not worked', gst: '0%' },
  { code: '7103', description: 'Precious or semi-precious stones (other)', gst: '0%' },
  { code: '7104', description: 'Synthetic or reconstructed precious or semi-precious', gst: '12%' },
  { code: '7105', description: 'Dust and powder of precious or semi-precious stones', gst: '0%' },
  { code: '7108', description: 'Gold including platinum-group metals', gst: '0%' },
  { code: '7110', description: 'Platinum, palladium and other platinum-group metals', gst: '0%' },
  { code: '7112', description: 'Waste and scrap of precious metal or clad precious metal', gst: '0%' },
  { code: '7113', description: 'Articles of jewellery and parts thereof', gst: '28%' },
  { code: '7114', description: 'Articles of precious metal or clad precious metal', gst: '28%' },
  { code: '7115', description: 'Other articles of precious metal or clad precious metal', gst: '28%' },
  { code: '7201', description: 'Pig iron and spiegeleisen', gst: '0%' },
  { code: '7202', description: 'Ferroalloys', gst: '0%' },
  { code: '7203', description: 'Ferrous products obtained by direct reduction of ore', gst: '0%' },
  { code: '7204', description: 'Waste and scrap of iron or steel', gst: '5%' },
  { code: '7205', description: 'Remelted scrap ingots of iron or steel', gst: '5%' },
  { code: '7206', description: 'Iron powders and sponges', gst: '5%' },
  { code: '7207', description: 'Semi-finished products of iron or non-alloy steel', gst: '0%' },
  { code: '7208', description: 'Flat-rolled products of iron or non-alloy steel', gst: '0%' },
  { code: '7209', description: 'Flat-rolled products of iron or non-alloy steel', gst: '0%' },
  { code: '7210', description: 'Flat-rolled products of iron or non-alloy steel', gst: '0%' },
  { code: '7211', description: 'Bars and rods of iron or non-alloy steel', gst: '0%' },
  { code: '7212', description: 'Flat-rolled products of iron or non-alloy steel', gst: '0%' },
  { code: '7213', description: 'Hot-rolled bars and rods of iron or non-alloy steel', gst: '0%' },
  { code: '7214', description: 'Other bars and rods of iron or non-alloy steel', gst: '0%' },
  { code: '7215', description: 'Other bars and rods of iron or non-alloy steel', gst: '0%' },
  { code: '7216', description: 'Angles, shapes and sections of iron or non-alloy steel', gst: '0%' },
  { code: '7217', description: 'Wire of iron or non-alloy steel', gst: '0%' },
  { code: '7218', description: 'Semi-finished products of stainless steel', gst: '0%' },
  { code: '7219', description: 'Flat-rolled products of stainless steel', gst: '0%' },
  { code: '7220', description: 'Flat-rolled products of stainless steel', gst: '0%' },
  { code: '7221', description: 'Bars and rods of stainless steel', gst: '0%' },
  { code: '7222', description: 'Other bars and rods of stainless steel', gst: '0%' },
  { code: '7223', description: 'Wire of stainless steel', gst: '0%' },
  { code: '7224', description: 'Semi-finished products of other alloy steel', gst: '0%' },
  { code: '7225', description: 'Flat-rolled products of other alloy steel', gst: '0%' },
  { code: '7226', description: 'Other flat-rolled products of other alloy steel', gst: '0%' },
  { code: '7227', description: 'Bars and rods of other alloy steel', gst: '0%' },
  { code: '7228', description: 'Other bars and rods of other alloy steel', gst: '0%' },
  { code: '7229', description: 'Wire of other alloy steel', gst: '0%' },
  { code: '7301', description: 'Tubes, pipes and hollow profiles of cast iron', gst: '5%' },
  { code: '7302', description: 'Tubes, pipes of iron or steel', gst: '5%' },
  { code: '7303', description: 'Other tubes and pipes of iron or steel', gst: '5%' },
  { code: '7304', description: 'Other tubes and pipes of iron or steel', gst: '5%' },
  { code: '7305', description: 'Other tubes and pipes of iron or steel', gst: '5%' },
  { code: '7306', description: 'Other tubes and pipes of iron or steel', gst: '5%' },
  { code: '7307', description: 'Tube and pipe fittings of iron or steel', gst: '12%' },
  { code: '7308', description: 'Structures of iron or steel; plates, rods, angles', gst: '12%' },
  { code: '7309', description: 'Reservoirs, tanks, vats and similar of iron or steel', gst: '12%' },
  { code: '7310', description: 'Tanks, casks, drums, cans and similar of iron or steel', gst: '12%' },
  { code: '7311', description: 'Containers for compressed or liquefied gas', gst: '12%' },
  { code: '7312', description: 'Stranded wire, ropes, cables of iron or steel', gst: '12%' },
  { code: '7313', description: 'Barbed wire of iron or steel', gst: '12%' },
  { code: '7314', description: 'Cloth (including endless bands) of iron or steel', gst: '12%' },
  { code: '7315', description: 'Chain and parts thereof of iron or steel', gst: '12%' },
  { code: '7316', description: 'Anchors, grapnels and parts thereof of iron or steel', gst: '12%' },
  { code: '7317', description: 'Nails, tacks, screws, bolts, nuts of iron or steel', gst: '12%' },
  { code: '7318', description: 'Other fasteners of iron or steel', gst: '12%' },
  { code: '7319', description: 'Sewing needles, bodkins, crochet hooks of iron or steel', gst: '12%' },
  { code: '7320', description: 'Springs of iron or steel', gst: '12%' },
  { code: '7321', description: 'Stoves, ranges, grates and similar heating appliances', gst: '18%' },
  { code: '7322', description: 'Radiators and heat exchange apparatus of iron or steel', gst: '12%' },
  { code: '7323', description: 'Articles of iron or steel (other domestic use)', gst: '18%' },
  { code: '7324', description: 'Sanitary ware of iron or steel', gst: '18%' },
  { code: '7325', description: 'Cast articles of iron or steel', gst: '12%' },
  { code: '7326', description: 'Other articles of iron or steel', gst: '12%' },
  { code: '7401', description: 'Copper mattes; cement copper (precipitated copper)', gst: '2.5%' },
  { code: '7402', description: 'Unrefined copper; copper anodes for refining', gst: '2.5%' },
  { code: '7403', description: 'Refined copper and copper alloys, unwrought', gst: '2.5%' },
  { code: '7404', description: 'Copper waste and scrap', gst: '2.5%' },
  { code: '7405', description: 'Master alloys of copper', gst: '5%' },
  { code: '7406', description: 'Copper powders and flakes', gst: '5%' },
  { code: '7407', description: 'Copper bars, rods and profiles', gst: '5%' },
  { code: '7408', description: 'Copper wire', gst: '5%' },
  { code: '7409', description: 'Copper plates, sheets and strip of a thickness', gst: '5%' },
  { code: '7410', description: 'Copper foil', gst: '5%' },
  { code: '7411', description: 'Tubes and pipes of copper', gst: '5%' },
  { code: '7412', description: 'Copper tube and pipe fittings', gst: '5%' },
  { code: '7413', description: 'Stranded wire, ropes and cables, of copper', gst: '5%' },
  { code: '7414', description: 'Cloth (including endless bands) of copper wire', gst: '5%' },
  { code: '7415', description: 'Nails, tacks, screws and bolts, of copper', gst: '12%' },
  { code: '7416', description: 'Other articles of copper', gst: '12%' },
  { code: '7417', description: 'Copper articles of a kind', gst: '12%' },
  { code: '7501', description: 'Nickel mattes, nickel oxide sinters and other intermediate', gst: '5%' },
  { code: '7502', description: 'Nickel, unwrought', gst: '5%' },
  { code: '7503', description: 'Nickel waste and scrap', gst: '5%' },
  { code: '7504', description: 'Nickel powders and flakes', gst: '5%' },
  { code: '7505', description: 'Nickel bars, rods, profiles and wire', gst: '5%' },
  { code: '7506', description: 'Nickel plates, sheets, strip and foil', gst: '5%' },
  { code: '7507', description: 'Tubes, pipes and tube and pipe fittings, of nickel', gst: '5%' },
  { code: '7508', description: 'Other articles of nickel', gst: '12%' },
  { code: '7601', description: 'Aluminium, unwrought', gst: '0%' },
  { code: '7602', description: 'Aluminium waste and scrap', gst: '5%' },
  { code: '7603', description: 'Aluminium powders and flakes', gst: '5%' },
  { code: '7604', description: 'Aluminium bars, rods and profiles', gst: '5%' },
  { code: '7605', description: 'Aluminium wire', gst: '5%' },
  { code: '7606', description: 'Aluminium plates, sheets and strip', gst: '5%' },
  { code: '7607', description: 'Aluminium foil', gst: '5%' },
  { code: '7608', description: 'Tubes and pipes of aluminium', gst: '5%' },
  { code: '7609', description: 'Tube and pipe fittings of aluminium', gst: '5%' },
  { code: '7610', description: 'Structures of aluminium; plates, rods, profiles', gst: '12%' },
  { code: '7611', description: 'Reservoirs, tanks and similar of aluminium', gst: '12%' },
  { code: '7612', description: 'Cans of aluminium', gst: '12%' },
  { code: '7613', description: 'Articles of aluminium (other)', gst: '12%' },
  { code: '7614', description: 'Stranded wire, ropes, cables, of aluminium', gst: '5%' },
  { code: '7615', description: 'Nails, tacks, screws, bolts, nuts of aluminium', gst: '12%' },
  { code: '7616', description: 'Other articles of aluminium', gst: '12%' },
  { code: '7701', description: 'Zinc unwrought', gst: '2.5%' },
  { code: '7702', description: 'Zinc waste and scrap', gst: '5%' },
  { code: '7703', description: 'Zinc powders and flakes', gst: '5%' },
  { code: '7704', description: 'Zinc bars, rods, profiles and wire', gst: '5%' },
  { code: '7705', description: 'Zinc plates, sheets, strip and foil', gst: '5%' },
  { code: '7706', description: 'Tubes, pipes and tube and pipe fittings of zinc', gst: '5%' },
  { code: '7707', description: 'Other articles of zinc', gst: '12%' },
  { code: '7801', description: 'Tin unwrought', gst: '5%' },
  { code: '7802', description: 'Tin waste and scrap', gst: '5%' },
  { code: '7803', description: 'Tin powders and flakes', gst: '5%' },
  { code: '7804', description: 'Tin bars, rods, profiles and wire', gst: '5%' },
  { code: '7805', description: 'Tin plates, sheets and strip', gst: '5%' },
  { code: '7806', description: 'Tin foil', gst: '5%' },
  { code: '7807', description: 'Other articles of tin', gst: '12%' },
  { code: '7901', description: 'Unwrought lead', gst: '2.5%' },
  { code: '7902', description: 'Lead waste and scrap', gst: '5%' },
  { code: '7903', description: 'Lead powders and flakes', gst: '5%' },
  { code: '7904', description: 'Lead bars, rods, profiles and wire', gst: '5%' },
  { code: '7905', description: 'Lead plates, sheets, strip and foil', gst: '5%' },
  { code: '7906', description: 'Lead tubes, pipes and tube and pipe fittings', gst: '5%' },
  { code: '7907', description: 'Other articles of lead', gst: '12%' },
  { code: '8001', description: 'Tin, unwrought', gst: '5%' },
  { code: '8002', description: 'Tin waste and scrap', gst: '5%' },
  { code: '8003', description: 'Tin coating bars', gst: '5%' },
  { code: '8004', description: 'Tin coating ingots', gst: '5%' },
  { code: '8005', description: 'Tin coating sheets and plates', gst: '5%' },
  { code: '8006', description: 'Other tin articles', gst: '12%' },
  { code: '8101', description: 'Manganese and articles thereof', gst: '5%' },
  { code: '8102', description: 'Magnesium and articles thereof', gst: '5%' },
  { code: '8103', description: 'Chromium and articles thereof', gst: '5%' },
  { code: '8104', description: 'Germanium and articles thereof', gst: '5%' },
  { code: '8105', description: 'Vanadium and articles thereof', gst: '5%' },
  { code: '8106', description: 'Cobalt mattes and cobalt; articles thereof', gst: '2.5%' },
  { code: '8107', description: 'Bismuth and articles thereof', gst: '5%' },
  { code: '8108', description: 'Titanium and articles thereof', gst: '5%' },
  { code: '8109', description: 'Zirconium and articles thereof', gst: '5%' },
  { code: '8110', description: 'Hafnium; rhenium; gallium; indium; thallium and articles', gst: '5%' },
  { code: '8111', description: 'Tungsten (wolfram) and articles thereof', gst: '5%' },
  { code: '8112', description: 'Molybdenum and articles thereof', gst: '5%' },
  { code: '8301', description: 'Padlocks and locks (key, combination or electrically operated)', gst: '12%' },
  { code: '8302', description: 'Base metal mountings, fittings and similar', gst: '12%' },
  { code: '8303', description: 'Armoured or reinforced safes and cash boxes', gst: '18%' },
  { code: '8304', description: 'Filing cabinets and similar', gst: '18%' },
  { code: '8305', description: 'Fittings for loose-leaf binders or files', gst: '18%' },
  { code: '8306', description: 'Bells, gongs and the like', gst: '12%' },
  { code: '8307', description: 'Flexible tubing of base metal', gst: '12%' },
  { code: '8308', description: 'Clasps, frames with clasps, buckles and similar', gst: '12%' },
  { code: '8309', description: 'Stoppers, caps and lids of base metal', gst: '12%' },
  { code: '8310', description: 'Sign-plates, name-plates and house-plates', gst: '12%' },
  { code: '8311', description: 'Wire, rods, tubes, plates, angles, shapes', gst: '12%' },
  { code: '8401', description: 'Steam turbines and other vapour turbines', gst: '12%' },
  { code: '8402', description: 'Steam boilers and hot water boilers', gst: '12%' },
  { code: '8403', description: 'Central heating boilers (other than steam boilers)', gst: '12%' },
  { code: '8404', description: 'Auxiliary plant for boilers', gst: '12%' },
  { code: '8405', description: 'Producer gas generators and acetylene gas generators', gst: '12%' },
  { code: '8406', description: 'Steam turbines and other vapour turbines', gst: '12%' },
  { code: '8407', description: 'Spark-ignition reciprocating piston engines', gst: '12%' },
  { code: '8408', description: 'Compression-ignition internal combustion piston engines', gst: '12%' },
  { code: '8409', description: 'Parts suitable for use solely or principally with engines', gst: '12%' },
  { code: '8410', description: 'Hydraulic turbines, water wheels and regulators', gst: '12%' },
  { code: '8411', description: 'Turbojets; turbopropellers and other gas turbines', gst: '12%' },
  { code: '8412', description: 'Other engines and motors', gst: '12%' },
  { code: '8413', description: 'Pumps for liquids; liquid elevators', gst: '12%' },
  { code: '8414', description: 'Air or vacuum pumps, air or other gas compressors', gst: '12%' },
  { code: '8415', description: 'Air conditioning machines', gst: '28%' },
  { code: '8416', description: 'Furnace burners for liquid fuel or for gas', gst: '12%' },
  { code: '8417', description: 'Industrial or laboratory furnaces and ovens', gst: '12%' },
  { code: '8418', description: 'Refrigerating or freezing equipment', gst: '28%' },
  { code: '8419', description: 'Machinery, plant or laboratory apparatus', gst: '12%' },
  { code: '8420', description: 'Calendering or other rolling machines', gst: '12%' },
  { code: '8421', description: 'Centrifuges; filtering or purifying machinery', gst: '12%' },
  { code: '8422', description: 'Dish washing machines; machinery', gst: '28%' },
  { code: '8423', description: 'Weighing machinery', gst: '12%' },
  { code: '8424', description: 'Mechanical appliances (other) for spraying, dispersing', gst: '12%' },
  { code: '8425', description: 'Pulley tackle and hoists (other than skip hoists)', gst: '12%' },
  { code: '8426', description: 'Ship\'s derricks; cranes; mobile lifting frames', gst: '12%' },
  { code: '8427', description: 'Fork-lift trucks; other works trucks', gst: '12%' },
  { code: '8428', description: 'Other lifting, loading, unloading machinery', gst: '12%' },
  { code: '8429', description: 'Self-propelled bulldozers, graders, rollers', gst: '12%' },
  { code: '8430', description: 'Other moving, grading, leveling machinery', gst: '12%' },
  { code: '8431', description: 'Parts suitable for use with machinery', gst: '12%' },
  { code: '8432', description: 'Agricultural machinery for soil preparation or tillage', gst: '0%' },
  { code: '8433', description: 'Harvesting or threshing machinery', gst: '0%' },
  { code: '8434', description: 'Dairy machinery', gst: '0%' },
  { code: '8435', description: 'Presses, crushers and similar machinery', gst: '0%' },
  { code: '8436', description: 'Other agricultural machinery (other)', gst: '0%' },
  { code: '8437', description: 'Machines for cleaning, sorting, grading food products', gst: '0%' },
  { code: '8438', description: 'Machinery not specified elsewhere', gst: '12%' },
  { code: '8439', description: 'Machinery for making cellulose pulp', gst: '12%' },
  { code: '8440', description: 'Machinery for paper making', gst: '12%' },
  { code: '8441', description: 'Machinery for making articles of paper pulp', gst: '12%' },
  { code: '8442', description: 'Machinery, apparatus and equipment of a kind', gst: '12%' },
  { code: '8443', description: 'Machinery for making up paper, paperboard', gst: '12%' },
  { code: '8444', description: 'Machinery for extruding, drawing, texturing', gst: '12%' },
  { code: '8445', description: 'Machinery for preparing textile fibres', gst: '12%' },
  { code: '8446', description: 'Weaving machines (looms)', gst: '12%' },
  { code: '8447', description: 'Knitting machines', gst: '12%' },
  { code: '8448', description: 'Auxiliary machinery', gst: '12%' },
  { code: '8449', description: 'Machinery for the manufacture of felt or nonwovens', gst: '12%' },
  { code: '8450', description: 'Washing machines for textile materials', gst: '28%' },
  { code: '8451', description: 'Machinery of a kind used in the textile industry', gst: '12%' },
  { code: '8452', description: 'Sewing machines', gst: '12%' },
  { code: '8453', description: 'Machinery for preparing, tanning or working leather', gst: '12%' },
  { code: '8454', description: 'Converters, ladles, ingot moulds', gst: '12%' },
  { code: '8455', description: 'Metal rolling mills; rolls for such mills', gst: '12%' },
  { code: '8456', description: 'Machine tools for removing metal', gst: '12%' },
  { code: '8457', description: 'Numerically controlled machine tools', gst: '12%' },
  { code: '8458', description: 'Lathes for removing metal', gst: '12%' },
  { code: '8459', description: 'Machine tools for boring, milling machinery', gst: '12%' },
  { code: '8460', description: 'Machine tools for grinding or finishing machinery', gst: '12%' },
  { code: '8461', description: 'Other machine tools', gst: '12%' },
  { code: '8462', description: 'Machine tools for working metal without removing', gst: '12%' },
  { code: '8463', description: 'Machine tools for working stone, ceramic minerals', gst: '12%' },
  { code: '8464', description: 'Machine tools for working wood, cork, bone', gst: '12%' },
  { code: '8465', description: 'Machine tools (other) not specified elsewhere', gst: '12%' },
  { code: '8466', description: 'Parts and accessories for machine tools', gst: '12%' },
  { code: '8467', description: 'Tools for working in the hand, pneumatic', gst: '12%' },
  { code: '8468', description: 'Machinery and apparatus for soldering, brazing', gst: '12%' },
  { code: '8469', description: 'Typewriters and word-processing machines', gst: '12%' },
  { code: '8470', description: 'Calculating machines; accounting machines', gst: '12%' },
  { code: '8471', description: 'Automatic data processing machines', gst: '5%' },
  { code: '8472', description: 'Office machines (other)', gst: '12%' },
  { code: '8473', description: 'Parts and accessories (other) for office machines', gst: '12%' },
  { code: '8474', description: 'Machinery for sorting, screening, separating', gst: '12%' },
  { code: '8475', description: 'Machinery for assembling electrical or electronic apparatus', gst: '12%' },
  { code: '8476', description: 'Automatic goods-vending machines', gst: '28%' },
  { code: '8477', description: 'Machinery for working rubber or plastics', gst: '12%' },
  { code: '8478', description: 'Machinery for preparing or making tobacco products', gst: '12%' },
  { code: '8479', description: 'Machines and mechanical appliances (other)', gst: '12%' },
  { code: '8480', description: 'Moulds', gst: '12%' },
  { code: '8481', description: 'Taps, cocks, valves and similar appliances', gst: '12%' },
  { code: '8482', description: 'Ball or roller bearings', gst: '12%' },
  { code: '8483', description: 'Shafts, cranks, bearing housings and similar', gst: '12%' },
  { code: '8484', description: 'Gaskets and similar seals', gst: '12%' },
  { code: '8485', description: 'Machinery parts not specified elsewhere', gst: '12%' },
  { code: '8486', description: 'Machines and apparatus for integrated circuits', gst: '5%' },
  { code: '8487', description: 'Machinery parts not specified elsewhere', gst: '12%' },
  { code: '8501', description: 'Electric motors', gst: '12%' },
  { code: '8502', description: 'Electric generating sets', gst: '12%' },
  { code: '8503', description: 'Parts suitable for use with electric motors', gst: '12%' },
  { code: '8504', description: 'Electrical transformers and inductors', gst: '12%' },
  { code: '8505', description: 'Electro-magnets', gst: '12%' },
  { code: '8506', description: 'Primary cells and primary batteries', gst: '12%' },
  { code: '8507', description: 'Electric accumulators (secondary cells)', gst: '12%' },
  { code: '8508', description: 'Electrostatic machines and apparatus', gst: '12%' },
  { code: '8509', description: 'Electro-heating apparatus', gst: '28%' },
  { code: '8510', description: 'Shavers and hair clippers with self-contained', gst: '28%' },
  { code: '8511', description: 'Electrical apparatus for making and breaking circuits', gst: '12%' },
  { code: '8512', description: 'Electrical apparatus for switching, controlling', gst: '12%' },
  { code: '8513', description: 'Portable electric lamps designed to function', gst: '12%' },
  { code: '8514', description: 'Industrial or laboratory electric furnaces and ovens', gst: '12%' },
  { code: '8515', description: 'Electric machines and apparatus for soldering', gst: '12%' },
  { code: '8516', description: 'Electric instantaneous or storage water heaters', gst: '28%' },
  { code: '8517', description: 'Telephone sets; telephones for cellular networks', gst: '5%' },
  { code: '8518', description: 'Microphones and stands therefor', gst: '12%' },
  { code: '8519', description: 'Sound recording or similar machines', gst: '12%' },
  { code: '8520', description: 'Magnetic tape or other recorded media', gst: '12%' },
  { code: '8521', description: 'Video recording or reproducing apparatus', gst: '12%' },
  { code: '8522', description: 'Parts and accessories for machines', gst: '12%' },
  { code: '8523', description: 'Discs, tapes, solid-state storage devices', gst: '5%' },
  { code: '8524', description: 'Records, tapes and other recorded media', gst: '12%' },
  { code: '8525', description: 'Transmission apparatus for radio-telephony', gst: '5%' },
  { code: '8526', description: 'Radar apparatus and radio navigational aid apparatus', gst: '5%' },
  { code: '8527', description: 'Reception apparatus for radio-telephony', gst: '12%' },
  { code: '8528', description: 'Reception apparatus for television', gst: '12%' },
  { code: '8529', description: 'Parts suitable for use with receiving apparatus', gst: '12%' },
  { code: '8530', description: 'Electrical signaling, safety and traffic-control', gst: '12%' },
  { code: '8531', description: 'Electric sound or visual signaling apparatus', gst: '12%' },
  { code: '8532', description: 'Electrical capacitors', gst: '12%' },
  { code: '8533', description: 'Electrical resistors', gst: '12%' },
  { code: '8534', description: 'Printed circuits', gst: '5%' },
  { code: '8535', description: 'Electrical apparatus for switching or protecting', gst: '12%' },
  { code: '8536', description: 'Electrical apparatus for switching or protecting', gst: '12%' },
  { code: '8537', description: 'Boards, panels, consoles, desks, cabinets', gst: '12%' },
  { code: '8538', description: 'Parts suitable for use solely or principally', gst: '12%' },
  { code: '8539', description: 'Lamps and lighting fittings including searchlights', gst: '12%' },
  { code: '8540', description: 'Thermionic, cold cathode or photo-cathode valves', gst: '12%' },
  { code: '8541', description: 'Semiconductor devices; photosensitive semiconductor devices', gst: '5%' },
  { code: '8542', description: 'Electronic integrated circuits', gst: '5%' },
  { code: '8543', description: 'Electrical machines and apparatus (other)', gst: '12%' },
  { code: '8544', description: 'Insulated (including enameled or anodized) wire', gst: '12%' },
  { code: '8545', description: 'Carbon electrodes, carbon brushes', gst: '12%' },
  { code: '8546', description: 'Electrical insulators', gst: '12%' },
  { code: '8547', description: 'Insulating fittings of ceramics', gst: '12%' },
  { code: '8548', description: 'Waste and scrap of primary cells, primary batteries', gst: '12%' },
  { code: '8601', description: 'Rail locomotives and tender cars', gst: '5%' },
  { code: '8602', description: 'Rail or tramway freight cars (wagons)', gst: '5%' },
  { code: '8603', description: 'Rail or tramway passenger cars', gst: '5%' },
  { code: '8604', description: 'Rail or tramway track fixtures and fittings', gst: '5%' },
  { code: '8605', description: 'Rail or tramway rolling stock (other)', gst: '5%' },
  { code: '8606', description: 'Rail or tramway rolling stock (other)', gst: '5%' },
  { code: '8607', description: 'Parts of rail or tramway locomotives or rolling stock', gst: '5%' },
  { code: '8608', description: 'Rail or tramway track and structures', gst: '5%' },
  { code: '8609', description: 'Containers specially designed and equipped', gst: '5%' },
  { code: '8701', description: 'Tractors', gst: '12%' },
  { code: '8702', description: 'Motor vehicles for the transport of ten or more persons', gst: '28%' },
  { code: '8703', description: 'Motor cars and other motor vehicles principally designed', gst: '28%' },
  { code: '8704', description: 'Motor vehicles for the transport of goods', gst: '28%' },
  { code: '8705', description: 'Special purpose motor vehicles (other)', gst: '28%' },
  { code: '8706', description: 'Chassis fitted with engines, for motor vehicles', gst: '28%' },
  { code: '8707', description: 'Bodies for motor vehicles', gst: '28%' },
  { code: '8708', description: 'Parts and accessories of motor vehicles', gst: '28%' },
  { code: '8709', description: 'Works trucks, self-propelled, not fitted', gst: '28%' },
  { code: '8710', description: 'Tanks and armoured fighting vehicles', gst: '28%' },
  { code: '8711', description: 'Motorcycles and motor scooters', gst: '28%' },
  { code: '8712', description: 'Bicycles and other cycles', gst: '12%' },
  { code: '8713', description: 'Carriages for disabled persons; other vehicles', gst: '5%' },
  { code: '8714', description: 'Parts and accessories of vehicles', gst: '12%' },
  { code: '8716', description: 'Trailers and semi-trailers; other vehicles', gst: '28%' },
  { code: '8801', description: 'Balloons and airships', gst: '5%' },
  { code: '8802', description: 'Aircraft and spacecraft', gst: '5%' },
  { code: '8803', description: 'Parts of aircraft or spacecraft', gst: '5%' },
  { code: '8804', description: 'Parachutes and parts thereof', gst: '12%' },
  { code: '8805', description: 'Aircraft launching gear; deck-arrestor or similar', gst: '12%' },
  { code: '8806', description: 'Aircraft and aerospace vehicle parts', gst: '5%' },
  { code: '8901', description: 'Cruise ships and other ships principally designed', gst: '5%' },
  { code: '8902', description: 'Fishing vessels; factory ships', gst: '5%' },
  { code: '8903', description: 'Tugs and pusher craft', gst: '5%' },
  { code: '8904', description: 'Vessels for the transport of goods', gst: '5%' },
  { code: '8905', description: 'Light-vessels, fire-floats, dredgers, floating cranes', gst: '5%' },
  { code: '8906', description: 'Other vessels, including warships and lifeboats', gst: '5%' },
  { code: '8907', description: 'Other floating structures', gst: '5%' },
  { code: '8908', description: 'Vessels and other floating structures for breaking up', gst: '5%' },
  { code: '9001', description: 'Optical fibres and optical fibre bundles', gst: '5%' },
  { code: '9002', description: 'Lenses, prisms, mirrors and other optical elements', gst: '5%' },
  { code: '9003', description: 'Frames and mountings for spectacles', gst: '12%' },
  { code: '9004', description: 'Spectacles, goggles and similar articles', gst: '12%' },
  { code: '9005', description: 'Binoculars, telescopes and other optical instruments', gst: '12%' },
  { code: '9006', description: 'Photographic cameras; photographic flashlight apparatus', gst: '12%' },
  { code: '9007', description: 'Cinematographic cameras and projectors', gst: '5%' },
  { code: '9008', description: 'Image projectors; photographic enlargers or reducers', gst: '12%' },
  { code: '9009', description: 'Photocopying apparatus; thermographic apparatus', gst: '12%' },
  { code: '9010', description: 'Apparatus and equipment for photographic laboratories', gst: '12%' },
  { code: '9011', description: 'Microscopes and parts thereof', gst: '5%' },
  { code: '9012', description: 'Microscopes and electron microscopes; parts', gst: '5%' },
  { code: '9013', description: 'Liquid crystal devices not constituting articles', gst: '5%' },
  { code: '9014', description: 'Surveying, hydrographic, navigational instruments', gst: '5%' },
  { code: '9015', description: 'Surveying, hydrographic, navigational instruments', gst: '5%' },
  { code: '9016', description: 'Balances of a sensitivity of 5 centgrammes or better', gst: '5%' },
  { code: '9017', description: 'Drawing, marking-out or mathematical calculating instruments', gst: '12%' },
  { code: '9018', description: 'Medical, surgical, dental or veterinary instruments', gst: '5%' },
  { code: '9019', description: 'Mechano-therapy apparatus; massage apparatus', gst: '5%' },
  { code: '9020', description: 'Other breathing appliances and gas masks', gst: '12%' },
  { code: '9024', description: 'Machines and appliances for testing the hardness', gst: '5%' },
  { code: '9025', description: 'Hydrometers and similar apparatus', gst: '5%' },
  { code: '9026', description: 'Instruments and apparatus for measuring or checking', gst: '5%' },
  { code: '9027', description: 'Instruments and apparatus for physical or chemical analysis', gst: '5%' },
  { code: '9028', description: 'Gas, liquid or electricity supply or production meters', gst: '5%' },
  { code: '9029', description: 'Revolution counters, production counters, taximeters', gst: '5%' },
  { code: '9030', description: 'Oscilloscopes and other instruments for measuring', gst: '5%' },
  { code: '9031', description: 'Measuring or checking instruments, appliances', gst: '5%' },
  { code: '9032', description: 'Automatic regulating or controlling instruments and apparatus', gst: '5%' },
  { code: '9033', description: 'Parts and accessories for instruments and apparatus', gst: '5%' },
  { code: '9101', description: 'Clocks with watch movements', gst: '12%' },
  { code: '9102', description: 'Watches; pocket-watches and other wrist watches', gst: '28%' },
  { code: '9103', description: 'Clocks with movements other than watch movements', gst: '12%' },
  { code: '9104', description: 'Clocks (other), including chronometers', gst: '12%' },
  { code: '9105', description: 'Other clocks', gst: '12%' },
  { code: '9106', description: 'Time of day recording apparatus; parkinson apparatus', gst: '12%' },
  { code: '9107', description: 'Time switches with clock or watch movement', gst: '12%' },
  { code: '9108', description: 'Watch movements with case', gst: '12%' },
  { code: '9109', description: 'Clock movements with case', gst: '12%' },
  { code: '9110', description: 'Complete watch or clock movements', gst: '12%' },
  { code: '9111', description: 'Watch cases and cases of a similar type for clocks', gst: '12%' },
  { code: '9112', description: 'Cases and other parts suitable for use with watch movements', gst: '12%' },
  { code: '9113', description: 'Watch straps, watch bands and watch bracelets', gst: '12%' },
  { code: '9114', description: 'Other parts of clocks or watches', gst: '12%' },
  { code: '9201', description: 'Pianos and harpsichords', gst: '12%' },
  { code: '9202', description: 'String musical instruments (other)', gst: '12%' },
  { code: '9205', description: 'Wind musical instruments', gst: '12%' },
  { code: '9206', description: 'Percussion musical instruments', gst: '12%' },
  { code: '9207', description: 'Musical instruments whose sound is produced', gst: '12%' },
  { code: '9208', description: 'Musical boxes; mechanisms; parts and accessories', gst: '12%' },
  { code: '9209', description: 'Parts, accessories of musical instruments', gst: '12%' },
  { code: '9301', description: 'Toys, games and sports equipment; parts and accessories', gst: '12%' },
  { code: '9302', description: 'Dolls representing only human beings', gst: '12%' },
  { code: '9303', description: 'Other toys; reduced-size (scale) models', gst: '12%' },
  { code: '9304', description: 'Video game consoles and machines', gst: '28%' },
  { code: '9305', description: 'Videogames; other games/amusements', gst: '28%' },
  { code: '9306', description: 'Carnival articles; conjuring apparatus; amusing novelties', gst: '12%' },
  { code: '9307', description: 'Automatic amusement machines', gst: '28%' },
  { code: '9308', description: 'Tricycles; other children playground equipment', gst: '12%' },
  { code: '9309', description: 'Parts and accessories not elsewhere specified', gst: '12%' },
  { code: '9310', description: 'Arrangements of model railway sets', gst: '12%' },
  { code: '9311', description: 'Other toys or games including video game consoles', gst: '12%' },
  { code: '9312', description: 'Articles for sport or outdoor games', gst: '12%' },
  { code: '9401', description: 'Seats (other than those of heading 9402)', gst: '28%' },
  { code: '9402', description: 'Medical, surgical, dental or veterinary furniture', gst: '5%' },
  { code: '9403', description: 'Other furniture and parts thereof', gst: '28%' },
  { code: '9404', description: 'Mattress supports; articles of bedding', gst: '12%' },
  { code: '9405', description: 'Lamps and lighting fittings (other)', gst: '28%' },
  { code: '9406', description: 'Prefabricated buildings', gst: '12%' },
  { code: '9501', description: 'Brooms and brushes', gst: '12%' },
  { code: '9502', description: 'Brooms and brushes made wholly or in part', gst: '12%' },
  { code: '9503', description: 'Feather dusters and similar articles', gst: '12%' },
  { code: '9504', description: 'Sieves, riddles and similar sifting devices', gst: '12%' },
  { code: '9505', description: 'Articles for sweeping; mops and similar cleaning articles', gst: '12%' },
  { code: '9506', description: 'Corkscrews and other articles', gst: '12%' },
  { code: '9507', description: 'Vacuum flasks and other vacuum vessels', gst: '12%' },
  { code: '9508', description: 'Mechanical lighters, not reloadable', gst: '28%' },
  { code: '9509', description: 'Matches (other than pyrophoric articles)', gst: '12%' },
  { code: '9510', description: 'Fire extinguishers whether or not charged', gst: '12%' },
  { code: '9511', description: 'Smoking pipes and cigar or cigarette holders', gst: '12%' },
  { code: '9512', description: 'Scent sprays and similar toilet sprays', gst: '28%' },
  { code: '9513', description: 'Apparel and clothing accessories (other)', gst: '12%' },
  { code: '9514', description: 'Umbrellas and sun umbrellas', gst: '12%' },
  { code: '9515', description: 'Umbrellas and sun umbrellas; other articles', gst: '12%' },
  { code: '9516', description: 'Whips and riding crops', gst: '12%' },
  { code: '9517', description: 'Canes, walking sticks, seat-sticks', gst: '12%' },
  { code: '9518', description: 'Corsets, braces, suspenders and similar articles', gst: '12%' },
  { code: '9519', description: 'Corsets, braces, suspenders and similar articles', gst: '12%' },
  { code: '9520', description: 'Tailors dummies and other articles', gst: '12%' },
  { code: '9601', description: 'Worked ivory, bone, tortoiseshell, horn', gst: '12%' },
  { code: '9602', description: 'Works of mother-of-pearl or shell', gst: '12%' },
  { code: '9603', description: 'Articles of bone', gst: '12%' },
  { code: '9604', description: 'Articles of meerschaum; articles of mineral materials', gst: '12%' },
  { code: '9605', description: 'Articles of jet (and mineral substitutes for jet)', gst: '12%' },
  { code: '9606', description: 'Buttons', gst: '12%' },
  { code: '9607', description: 'Slide fasteners', gst: '12%' },
  { code: '9608', description: 'Ball-point pens; felt-tipped and other porous-tipped pens', gst: '12%' },
  { code: '9609', description: 'Pencils, crayons, pencil leads, pastels', gst: '12%' },
  { code: '9610', description: 'Slates and boards with writing or drawing surfaces', gst: '12%' },
  { code: '9611', description: 'Date, sealing or numbering stamps', gst: '12%' },
  { code: '9612', description: 'Perforating or stapling machines', gst: '12%' },
  { code: '9613', description: 'Lighters (other than pyrophoric articles)', gst: '28%' },
  { code: '9614', description: 'Pipes and bowls for smoking', gst: '28%' },
  { code: '9615', description: 'Hair brushes, tooth brushes, nail brushes', gst: '18%' },
  { code: '9616', description: 'Monopods, bipods, tripods and similar articles', gst: '28%' },
  { code: '9617', description: 'Vacuum flasks and other vacuum vessels', gst: '12%' },
  { code: '9618', description: 'Tailors dummies', gst: '12%' },
  { code: '9619', description: 'Sanitary towels (pads) and tampons', gst: '0%' },
  { code: '9620', description: 'Moleskin and similar articles', gst: '12%' },
  { code: '9621', description: 'Corsets, braces, suspenders', gst: '12%' },
  { code: '9622', description: 'Apparel and clothing accessories', gst: '12%' },
  { code: '9623', description: 'Umbrellas and sun umbrellas', gst: '12%' },
  { code: '9624', description: 'Apparel and clothing accessories', gst: '12%' },
  { code: '9625', description: 'Other articles', gst: '12%' },
  { code: '9701', description: 'Paintings, drawings and pastels', gst: '5%' },
  { code: '9702', description: 'Original engravings, prints and lithographs', gst: '5%' },
  { code: '9703', description: 'Original sculptures and statuary', gst: '5%' },
  { code: '9704', description: 'Collections and collector\'s pieces of zoological', gst: '0%' },
  { code: '9705', description: 'Antiques of an age exceeding one hundred years', gst: '5%' },
  { code: '9801', description: 'Goods of chapter 98', gst: '5%' },
  { code: '9802', description: 'Articles manufactured from raw materials', gst: '5%' },
  { code: '9803', description: 'Articles for temporary importation', gst: '0%' },
  { code: '9804', description: 'Goods of chapter 98 (other)', gst: '5%' },
  { code: '9805', description: 'Articles intended for supply on board aircraft', gst: '0%' },
  { code: '9806', description: 'Ships and other vessels and floating structures', gst: '0%' },
  { code: '9807', description: 'Other goods', gst: '5%' }
];

document.addEventListener('DOMContentLoaded', function() {
  const searchInput = document.getElementById('hsnSearch');
  const resultsContainer = document.getElementById('hsnResults');

  if (searchInput) {
    searchInput.addEventListener('keyup', function() {
      const query = this.value.toLowerCase().trim();

      if (query.length === 0) {
        resultsContainer.innerHTML = '';
        return;
      }

      const results = hsnDatabase.filter(item => 
        item.code.includes(query) || 
        item.description.toLowerCase().includes(query)
      );

      if (results.length === 0) {
        resultsContainer.innerHTML = '<p class="alert alert-info">No HSN codes found. Check <a href="https://www.cbic.gov.in" target="_blank">CBIC website</a> for more codes.</p>';
      } else {
        resultsContainer.innerHTML = '<table class="line-items-table"><thead><tr><th>HSN/SAC Code</th><th>Description</th><th>GST Rate</th></tr></thead><tbody>' + 
          results.map(item => `
            <tr onclick="selectHsnCode('${item.code}', '${item.gst}')">
              <td><strong>${item.code}</strong></td>
              <td>${item.description}</td>
              <td>${item.gst}</td>
            </tr>
          `).join('') + 
          '</tbody></table>';
      }
    });
  }
});

function selectHsnCode(code, gst) {
  console.log('Selected HSN Code:', code, 'GST:', gst);
  // Can integrate with invoice form if needed
}
