// PDF Generation using jsPDF
// Load from CDN: https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js
// and https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js

function generatePDF(invoiceNumber, invoiceDate) {
  // Get form data
  const formData = {
    businessName: document.getElementById('businessName')?.value || '',
    gstin: document.getElementById('gstin')?.value || '',
    address: document.getElementById('businessAddress')?.value || '',
    state: document.getElementById('businessState')?.value || '',
    phone: document.getElementById('phone')?.value || '',
    email: document.getElementById('email')?.value || '',
    buyerName: document.getElementById('buyerName')?.value || '',
    buyerGstin: document.getElementById('buyerGstin')?.value || '',
    buyerAddress: document.getElementById('buyerAddress')?.value || '',
    buyerState: document.getElementById('buyerState')?.value || '',
    invoiceNumber: invoiceNumber,
    invoiceDate: invoiceDate,
    dueDate: document.getElementById('dueDate')?.value || '',
    invoiceType: document.getElementById('invoiceType')?.value || 'Tax Invoice',
    notes: document.getElementById('notes')?.value || '',
    terms: document.getElementById('terms')?.value || ''
  };

  // Get invoice summary data
  const summaryData = {
    subtotal: document.getElementById('subtotal')?.textContent || '0',
    cgst: document.getElementById('cgstAmount')?.textContent || '0',
    sgst: document.getElementById('sgstAmount')?.textContent || '0',
    igst: document.getElementById('igstAmount')?.textContent || '0',
    totalGst: document.getElementById('totalGstAmount')?.textContent || '0',
    grandTotal: document.getElementById('grandTotal')?.textContent || '0',
    amountInWords: document.getElementById('amountInWords')?.textContent || ''
  };

  // Get line items
  const lineItems = getLineItemsData();

  // Create PDF
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 15;

  // Header with logo and title
  doc.setFontSize(16);
  doc.setTextColor(26, 107, 60);
  doc.text('GST INVOICE', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 10;

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by InvoiceBana.in - Free GST Invoice Tool', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 8;

  // Divider line
  doc.setDrawColor(26, 107, 60);
  doc.line(15, yPosition, pageWidth - 15, yPosition);
  yPosition += 8;

  // Seller Details
  doc.setFontSize(10);
  doc.setTextColor(26, 107, 60);
  doc.text('SELLER DETAILS', 15, yPosition);
  yPosition += 6;

  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);
  doc.text(`Name: ${formData.businessName}`, 15, yPosition);
  yPosition += 4;
  doc.text(`GSTIN: ${formData.gstin || 'N/A'}`, 15, yPosition);
  yPosition += 4;
  doc.text(`Address: ${formData.address}`, 15, yPosition);
  yPosition += 4;
  doc.text(`State: ${formData.state}`, 15, yPosition);
  yPosition += 4;
  doc.text(`Phone: ${formData.phone}`, 15, yPosition);
  yPosition += 4;
  doc.text(`Email: ${formData.email}`, 15, yPosition);
  yPosition += 8;

  // Buyer Details
  doc.setFontSize(10);
  doc.setTextColor(26, 107, 60);
  doc.text('BUYER DETAILS', pageWidth / 2, 41);

  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);
  doc.text(`Name: ${formData.buyerName}`, pageWidth / 2, 47);
  doc.text(`GSTIN: ${formData.buyerGstin || 'N/A'}`, pageWidth / 2, 51);
  doc.text(`Address: ${formData.buyerAddress}`, pageWidth / 2, 55);
  doc.text(`State: ${formData.buyerState}`, pageWidth / 2, 59);

  yPosition = Math.max(yPosition, 67);

  // Invoice Details
  doc.setFontSize(10);
  doc.setTextColor(26, 107, 60);
  doc.text('INVOICE DETAILS', 15, yPosition);
  yPosition += 6;

  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);
  doc.text(`Invoice Number: ${formData.invoiceNumber}`, 15, yPosition);
  yPosition += 4;
  doc.text(`Date: ${formData.invoiceDate}`, 15, yPosition);
  yPosition += 4;
  doc.text(`Due Date: ${formData.dueDate || 'N/A'}`, 15, yPosition);
  yPosition += 4;
  doc.text(`Type: ${formData.invoiceType}`, 15, yPosition);
  yPosition += 8;

  // Line Items Table
  if (lineItems.length > 0) {
    const tableHeaders = ['Description', 'HSN/SAC', 'Qty', 'Unit', 'Rate', 'GST %', 'Amount'];
    const tableData = lineItems.map(item => [
      item.description,
      item.hsn,
      item.qty,
      item.unit,
      item.rate,
      item.gst,
      item.amount
    ]);

    doc.autoTable({
      head: [tableHeaders],
      body: tableData,
      startY: yPosition,
      margin: { left: 15, right: 15 },
      styles: {
        fontSize: 8,
        overflow: 'linebreak'
      },
      headStyles: {
        fillColor: [26, 107, 60],
        textColor: 255,
        fontStyle: 'bold'
      },
      alternateRowStyles: {
        fillColor: [248, 250, 249]
      }
    });

    yPosition = doc.lastAutoTable.finalY + 8;
  }

  // Summary
  doc.setFontSize(10);
  doc.setTextColor(26, 107, 60);
  doc.text('SUMMARY', 15, yPosition);
  yPosition += 6;

  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);
  doc.text(`Subtotal: ₹ ${summaryData.subtotal}`, 15, yPosition);
  yPosition += 4;

  if (document.getElementById('cgstAmount')) {
    doc.text(`CGST: ₹ ${summaryData.cgst}`, 15, yPosition);
    yPosition += 4;
    doc.text(`SGST: ₹ ${summaryData.sgst}`, 15, yPosition);
    yPosition += 4;
  } else if (document.getElementById('igstAmount')) {
    doc.text(`IGST: ₹ ${summaryData.igst}`, 15, yPosition);
    yPosition += 4;
  }

  doc.setFontSize(10);
  doc.setTextColor(26, 107, 60);
  doc.setFont(undefined, 'bold');
  doc.text(`Grand Total: ₹ ${summaryData.grandTotal}`, 15, yPosition);
  yPosition += 6;

  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);
  doc.setFont(undefined, 'normal');
  doc.text(`Amount in Words: ${summaryData.amountInWords}`, 15, yPosition);

  if (yPosition + 15 < pageHeight) {
    yPosition += 10;
    if (formData.notes) {
      doc.setFontSize(9);
      doc.setTextColor(26, 107, 60);
      doc.text('NOTES:', 15, yPosition);
      yPosition += 4;
      doc.setTextColor(0, 0, 0);
      const notesText = doc.splitTextToSize(formData.notes, pageWidth - 30);
      doc.text(notesText, 15, yPosition);
    }
  }

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text('This is a computer-generated invoice. Signature not required.', pageWidth / 2, pageHeight - 10, { align: 'center' });

  // Save PDF
  const fileName = `GST-Invoice-${formData.invoiceNumber}-${formData.invoiceDate}.pdf`;
  doc.save(fileName);

  return true;
}

function getLineItemsData() {
  const lineItems = [];
  const rows = document.querySelectorAll('.line-item-row');
  
  rows.forEach(row => {
    const description = row.querySelector('[data-field="description"]')?.value || '';
    const hsn = row.querySelector('[data-field="hsn"]')?.value || '';
    const qty = row.querySelector('[data-field="qty"]')?.value || '0';
    const unit = row.querySelector('[data-field="unit"]')?.value || '';
    const rate = row.querySelector('[data-field="rate"]')?.value || '0';
    const gst = row.querySelector('[data-field="gst"]')?.value || '0';
    const amount = parseFloat(qty) * parseFloat(rate);

    if (description || qty || rate) {
      lineItems.push({
        description,
        hsn,
        qty,
        unit,
        rate,
        gst,
        amount: amount.toFixed(2)
      });
    }
  });

  return lineItems;
}

// Convert number to words in Indian currency format
function numberToWords(num) {
  const ones = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine'];
  const teens = ['Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
  const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
  const scales = ['', 'Thousand', 'Million', 'Billion', 'Trillion'];

  if (num === 0) return 'Zero';

  let result = '';
  let scaleIndex = 0;

  while (num > 0) {
    const chunk = num % 1000;
    if (chunk !== 0) {
      result = convertHundreds(chunk, ones, teens, tens) + (scales[scaleIndex] ? ' ' + scales[scaleIndex] : '') + ' ' + result;
    }
    num = Math.floor(num / 1000);
    scaleIndex++;
  }

  return result.trim() + ' Only';
}

function convertHundreds(num, ones, teens, tens) {
  let result = '';
  
  const hundreds = Math.floor(num / 100);
  const remainder = num % 100;

  if (hundreds > 0) {
    result += ones[hundreds] + ' Hundred ';
  }

  if (remainder >= 10 && remainder < 20) {
    result += teens[remainder - 10];
  } else {
    const ten = Math.floor(remainder / 10);
    const one = remainder % 10;
    if (ten > 0) {
      result += tens[ten] + ' ';
    }
    if (one > 0) {
      result += ones[one];
    }
  }

  return result.trim();
}
